import type { Transaction, Customer, LoanEntry, TeamMember, Wallet } from './types'
import { format, subDays } from 'date-fns'

const today = format(new Date(), 'yyyy-MM-dd')
const yesterday = format(subDays(new Date(), 1), 'yyyy-MM-dd')

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-1',
    type: 'income',
    category_id: 'sale',
    amount: 2500,
    wallet_id: 'cash',
    date: today,
    time: '10:32',
    note_en: 'Samsung A15',
    note_ur: 'سیمسنگ اے 15',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${today}T10:32:00.000Z`,
    updated_at: `${today}T10:32:00.000Z`,
  },
  {
    id: 'txn-2',
    type: 'income',
    category_id: 'repair',
    amount: 800,
    wallet_id: 'jazzcash',
    date: today,
    time: '11:15',
    note_en: 'iPhone 15 screen repair',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${today}T11:15:00.000Z`,
    updated_at: `${today}T11:15:00.000Z`,
  },
  {
    id: 'txn-3',
    type: 'expense',
    category_id: 'purchase',
    amount: 1200,
    wallet_id: 'cash',
    date: today,
    time: '12:00',
    note_en: 'Shop supplies',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${today}T12:00:00.000Z`,
    updated_at: `${today}T12:00:00.000Z`,
  },
  {
    id: 'txn-4',
    type: 'income',
    category_id: 'sale',
    amount: 1500,
    wallet_id: 'easypaisa',
    date: today,
    time: '13:30',
    note_en: 'EasyPaisa in',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${today}T13:30:00.000Z`,
    updated_at: `${today}T13:30:00.000Z`,
  },
  {
    id: 'txn-5',
    type: 'expense',
    category_id: 'purchase',
    amount: 3000,
    wallet_id: 'jazzcash',
    date: today,
    time: '14:45',
    note_en: 'Supplier payment',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${today}T14:45:00.000Z`,
    updated_at: `${today}T14:45:00.000Z`,
  },
  {
    id: 'txn-6',
    type: 'income',
    category_id: 'sale',
    amount: 450,
    wallet_id: 'easypaisa',
    date: today,
    time: '15:20',
    note_en: 'USB cables x3',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${today}T15:20:00.000Z`,
    updated_at: `${today}T15:20:00.000Z`,
  },
  {
    id: 'txn-ob-cash',
    type: 'opening_balance',
    category_id: 'opening',
    amount: 15000,
    wallet_id: 'cash',
    date: yesterday,
    time: '09:00',
    note_en: 'Opening balance - Cash',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${yesterday}T09:00:00.000Z`,
    updated_at: `${yesterday}T09:00:00.000Z`,
  },
  {
    id: 'txn-ob-jazz',
    type: 'opening_balance',
    category_id: 'opening',
    amount: 8200,
    wallet_id: 'jazzcash',
    date: yesterday,
    time: '09:00',
    note_en: 'Opening balance - JazzCash',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${yesterday}T09:00:00.000Z`,
    updated_at: `${yesterday}T09:00:00.000Z`,
  },
  {
    id: 'txn-ob-easy',
    type: 'opening_balance',
    category_id: 'opening',
    amount: 3100,
    wallet_id: 'easypaisa',
    date: yesterday,
    time: '09:00',
    note_en: 'Opening balance - EasyPaisa',
    is_reversed: false,
    created_by: 'owner',
    created_at: `${yesterday}T09:00:00.000Z`,
    updated_at: `${yesterday}T09:00:00.000Z`,
  },
]

export const MOCK_CUSTOMERS: Customer[] = [
  { id: 'cust-1', name: 'Ahmed Khan', phone: '03112345678', created_at: yesterday },
  { id: 'cust-2', name: 'Bilal Ahmed', phone: '03223456789', created_at: yesterday },
  { id: 'cust-3', name: 'Sara Bibi', phone: '03334567890', created_at: yesterday },
]

export const MOCK_LOAN_ENTRIES: LoanEntry[] = [
  { id: 'loan-1', customer_id: 'cust-1', transaction_id: 'loan-txn-1', amount: 3500, direction: 'given', wallet_id: 'cash', date: yesterday, note_en: 'Mobile purchase', is_settled: false },
  { id: 'loan-2', customer_id: 'cust-2', transaction_id: 'loan-txn-2', amount: 2800, direction: 'given', wallet_id: 'jazzcash', date: yesterday, is_settled: false },
  { id: 'loan-3', customer_id: 'cust-3', transaction_id: 'loan-txn-3', amount: 500, direction: 'received', wallet_id: 'cash', date: yesterday, is_settled: false },
]

export const MOCK_TEAM: TeamMember[] = [
  { id: 'staff-1', name: 'Ahmad Raza', phone: '03119876543', role: 'manager', is_active: true, created_at: yesterday },
  { id: 'staff-2', name: 'Zain Khan', phone: '03225551234', role: 'staff', is_active: true, created_at: yesterday },
]
