export const BUSINESS_TYPES = [
  {
    id: 'mobile_shop',
    name_en: 'Mobile Shop',
    name_ur: 'موبائل شاپ',
    icon: '📱',
    default_items: [
      { id: 'b1', name_en: 'Samsung A15', name_ur: 'سیمسنگ اے 15' },
      { id: 'b2', name_en: 'iPhone 15 Back Glass', name_ur: 'آئی فون 15 بیک گلاس' },
      { id: 'b3', name_en: 'Screen Protector', name_ur: 'اسکرین پروٹیکٹر' },
      { id: 'b4', name_en: 'USB Cable', name_ur: 'یو ایس بی کیبل' },
      { id: 'b5', name_en: 'Phone Cover', name_ur: 'فون کور' },
      { id: 'b6', name_en: 'Charger', name_ur: 'چارجر' },
      { id: 'b7', name_en: 'Earphones', name_ur: 'ائرفون' },
      { id: 'b8', name_en: 'Battery', name_ur: 'بیٹری' },
    ],
    default_income_categories: ['Sale', 'Repair', 'Service', 'Commission'],
    default_expense_categories: ['Purchase', 'Rent', 'Electricity', 'Salary'],
  },
  {
    id: 'repair_shop',
    name_en: 'Repair Shop',
    name_ur: 'مرمت کی دکان',
    icon: '🔧',
    default_items: [
      { id: 'r1', name_en: 'Screen Replacement', name_ur: 'اسکرین تبدیلی' },
      { id: 'r2', name_en: 'Battery Replacement', name_ur: 'بیٹری تبدیلی' },
      { id: 'r3', name_en: 'Charging Port Fix', name_ur: 'چارجنگ پورٹ مرمت' },
      { id: 'r4', name_en: 'Speaker Repair', name_ur: 'اسپیکر مرمت' },
      { id: 'r5', name_en: 'Water Damage', name_ur: 'پانی کا نقصان' },
    ],
    default_income_categories: ['Repair', 'Service', 'Parts Sale'],
    default_expense_categories: ['Parts Purchase', 'Rent', 'Electricity'],
  },
  {
    id: 'garments',
    name_en: 'Garments Store',
    name_ur: 'کپڑے کی دکان',
    icon: '👕',
    default_items: [
      { id: 'g1', name_en: 'Shirt', name_ur: 'قمیص' },
      { id: 'g2', name_en: 'Trouser', name_ur: 'پتلون' },
      { id: 'g3', name_en: 'Shalwar Kameez', name_ur: 'شلوار قمیص' },
      { id: 'g4', name_en: 'Lawn Suit', name_ur: 'لان سوٹ' },
      { id: 'g5', name_en: 'Dupatta', name_ur: 'دوپٹہ' },
    ],
    default_income_categories: ['Sale', 'Stitching', 'Wholesale'],
    default_expense_categories: ['Stock Purchase', 'Rent', 'Electricity', 'Salary'],
  },
  {
    id: 'grocery',
    name_en: 'Grocery Store',
    name_ur: 'کریانہ اسٹور',
    icon: '🛒',
    default_items: [
      { id: 'k1', name_en: 'Rice (per kg)', name_ur: 'چاول (فی کلو)' },
      { id: 'k2', name_en: 'Flour (per kg)', name_ur: 'آٹا (فی کلو)' },
      { id: 'k3', name_en: 'Sugar (per kg)', name_ur: 'چینی (فی کلو)' },
      { id: 'k4', name_en: 'Oil (per liter)', name_ur: 'تیل (فی لیٹر)' },
      { id: 'k5', name_en: 'Milk (per liter)', name_ur: 'دودھ (فی لیٹر)' },
    ],
    default_income_categories: ['Sale', 'Wholesale'],
    default_expense_categories: ['Stock Purchase', 'Rent', 'Electricity'],
  },
  {
    id: 'freelancer',
    name_en: 'Freelancer',
    name_ur: 'فری لانسر',
    icon: '💻',
    default_items: [
      { id: 'f1', name_en: 'Web Design', name_ur: 'ویب ڈیزائن' },
      { id: 'f2', name_en: 'Logo Design', name_ur: 'لوگو ڈیزائن' },
      { id: 'f3', name_en: 'Data Entry', name_ur: 'ڈیٹا انٹری' },
      { id: 'f4', name_en: 'Content Writing', name_ur: 'مواد لکھنا' },
    ],
    default_income_categories: ['Project', 'Hourly', 'Commission'],
    default_expense_categories: ['Software', 'Internet', 'Equipment'],
  },
  {
    id: 'manufacturer',
    name_en: 'Manufacturer',
    name_ur: 'کارخانہ',
    icon: '🏭',
    default_items: [],
    default_income_categories: ['Product Sale', 'Wholesale', 'Export'],
    default_expense_categories: ['Raw Material', 'Labour', 'Electricity', 'Rent'],
  },
] as const
