export const COUNTRIES = [
  {
    code: 'PK',
    name_en: 'Pakistan',
    name_ur: 'پاکستان',
    flag: '🇵🇰',
    currency: 'PKR',
    currency_symbol: 'Rs.',
    phone_prefix: '+92',
    is_active: true,
    wallets: ['cash', 'jazzcash', 'easypaisa'],
  },
  {
    code: 'AE',
    name_en: 'UAE',
    flag: '🇦🇪',
    currency: 'AED',
    is_active: false,
    coming_soon: true,
  },
  {
    code: 'SA',
    name_en: 'Saudi Arabia',
    flag: '🇸🇦',
    currency: 'SAR',
    is_active: false,
    coming_soon: true,
  },
  {
    code: 'BD',
    name_en: 'Bangladesh',
    flag: '🇧🇩',
    currency: 'BDT',
    is_active: false,
    coming_soon: true,
  },
  {
    code: 'IN',
    name_en: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    is_active: false,
    coming_soon: true,
  },
] as const
