export const PERMISSIONS = {
  owner: {
    add_transaction: true,
    view_reports: true,
    manage_loan: true,
    manage_team: true,
    manage_subscription: true,
    daily_close: true,
    export_pdf: true,
    edit_settings: true,
    delete_transaction: true,
    view_all_records: true,
  },
  manager: {
    add_transaction: true,
    view_reports: true,
    manage_loan: true,
    manage_team: false,
    manage_subscription: false,
    daily_close: true,
    export_pdf: true,
    edit_settings: false,
    delete_transaction: false,
    view_all_records: true,
  },
  staff: {
    add_transaction: true,
    view_reports: false,
    manage_loan: false,
    manage_team: false,
    manage_subscription: false,
    daily_close: false,
    export_pdf: false,
    edit_settings: false,
    delete_transaction: false,
    view_all_records: false,
  },
} as const
