export const PLANS = [
  {
    id: 'starter',
    name_en: 'Starter',
    name_ur: 'اسٹارٹر',
    price_monthly: 0,
    price_annual: 0,
    currency: 'PKR',
    transaction_limit_monthly: 300,
    transaction_limit_daily_after: 5,
    voice_limit_daily: 3,
    grace_limit_daily: 5,
    max_users: 1,
    features: {
      invoice: false,
      pdf_export: false,
      csv_export: false,
      advanced_reports: false,
      priority_support: false,
      inventory: false,
      multi_user: false,
      custom_categories: true,
      daily_close: true,
      loan_management: true,
      wallet_management: true,
      customers: false,
    },
    badge_color: 'gray',
    is_recommended: false,
  },
  {
    id: 'growth',
    name_en: 'Growth',
    name_ur: 'گروتھ',
    price_monthly: 250,
    price_annual: 2500,
    annual_saving: 500,
    currency: 'PKR',
    transaction_limit_monthly: Infinity,
    transaction_limit_daily_after: Infinity,
    voice_limit_daily: 10,
    grace_limit_daily: 0,
    max_users: 1,
    features: {
      invoice: true,
      pdf_export: false,
      csv_export: false,
      advanced_reports: false,
      priority_support: false,
      inventory: false,
      multi_user: false,
      custom_categories: true,
      daily_close: true,
      loan_management: true,
      wallet_management: true,
      customers: false,
    },
    badge_color: 'blue',
    is_recommended: false,
  },
  {
    id: 'business',
    name_en: 'Business',
    name_ur: 'بزنس',
    price_monthly: 500,
    price_annual: 5000,
    annual_saving: 1000,
    currency: 'PKR',
    transaction_limit_monthly: Infinity,
    transaction_limit_daily_after: Infinity,
    voice_limit_daily: 25,
    grace_limit_daily: 0,
    max_users: 3,
    features: {
      invoice: true,
      pdf_export: true,
      csv_export: true,
      advanced_reports: true,
      priority_support: true,
      inventory: false,
      multi_user: true,
      custom_categories: true,
      daily_close: true,
      loan_management: true,
      wallet_management: true,
      customers: true,
    },
    badge_color: 'green',
    is_recommended: true,
  },
  {
    id: 'pro',
    name_en: 'Pro',
    name_ur: 'پرو',
    price_monthly: 1000,
    price_annual: 10000,
    annual_saving: 2000,
    currency: 'PKR',
    transaction_limit_monthly: Infinity,
    transaction_limit_daily_after: Infinity,
    voice_limit_daily: 50,
    grace_limit_daily: 0,
    max_users: 10,
    features: {
      invoice: true,
      pdf_export: true,
      csv_export: true,
      advanced_reports: true,
      priority_support: true,
      inventory: true,
      multi_user: true,
      custom_categories: true,
      daily_close: true,
      loan_management: true,
      wallet_management: true,
      customers: true,
    },
    badge_color: 'purple',
    is_recommended: false,
  },
] as const
